In [2]:
import pandas as pd

df = pd.read_csv("c:/Users/loydt/Downloads/traffic data.csv")

In [4]:
df.head()

,user_id,session_id,sign_in,name,demographic_age,demographic_age_group,demographic_gender,email,location,country,...,pages_visited,conversion_flag,conversion_type,traffic_source,product_purchased,revenue_$,payment_type,card_type,coupon_applied,bounce_flag
0,U10477,S000001,Email,Victor Navarro-Noël,31,Adult,Female,victornavarronoël251@hotmail.com,Rome,Italy,...,7,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,1
1,U01536,S000002,Email,王秀云,39,Adult,Female,王秀云617@gmail.com,Madrid,Spain,...,5,0,NCT,Social,NPP,0.0,NPT,NCAT,ND,0
2,U00107,S000003,Guest,Ucchal Sabharwal,68,Old,Male,Not Provided,Manchester,UK,...,7,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,0
3,U13886,S000004,Email,Virginie Schmitt,72,Old,Female,virginieschmitt827@gmail.com,Sydney,Australia,...,10,0,NCT,Social,NPP,0.0,NPT,NCAT,ND,0
4,U05926,S000005,Email,Cynthia Drake,51,Adult,No Answer,cynthiadrake47@hotmail.com,Mumbai,India,...,6,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                100 non-null    object
 1   session_id             100 non-null    object
 2   sign_in                100 non-null    object
 3   name                   100 non-null    object
 4   demographic_age        100 non-null    int64
 5   demographic_age_group  100 non-null    object
 6   demographic_gender     100 non-null    object
 7   email                  100 non-null    object
 8   location               100 non-null    object
 9   country                100 non-null    object
 10  device_type            100 non-null    object
 11  timestamp              100 non-null    object
 12  variant_group          100 non-null    object
 13  time_spent             100 non-null    float64
 14  pages_visited          100 non-null    int64
 15  conversion_flag        100 non-null    int64
 16  conversion_type        100 non-null    object
 17  traffic_source         100 non-null    object
 18  product_purchased      100 non-null    object
 19  revenue_$              100 non-null    float64
 20  payment_type           100 non-null    object
 21  card_type              100 non-null    object
 22  coupon_applied         100 non-null    object
 23  bounce_flag            100 non-null    int64
dtypes: float64(2), int64(4), object(18)
memory usage: 18.9+ KB

In [9]:
df.columns

Index(['user_id', 'session_id', 'sign_in', 'name', 'demographic_age',
       'demographic_age_group', 'demographic_gender', 'email', 'location',
       'country', 'device_type', 'timestamp', 'variant_group', 'time_spent',
       'pages_visited', 'conversion_flag', 'conversion_type', 'traffic_source',
       'product_purchased', 'revenue_$', 'payment_type', 'card_type',
       'coupon_applied', 'bounce_flag'],
      dtype='object')

In [30]:
df[['user_id', 'session_id', 'timestamp', 'time_spent']].isna().sum()

user_id       0
session_id    0
timestamp     0
time_spent    0
dtype: int64

In [31]:
df[['user_id', 'session_id', 'timestamp', 'time_spent']].duplicated().sum()

np.int64(0)

In [32]:
df['user_id'].unique()

array(['U10477', 'U01536', 'U00107', 'U13886', 'U05926', 'U05821',
       'U05314', 'U14984', 'U03594', 'U06917', 'U08798', 'U12484',
       'U09814', 'U12462', 'U06538', 'U03771', 'U03511', 'U06736',
       'U01236', 'U06571', 'U07974', 'U08321', 'U01344', 'U04916',
       'U06055', 'U10869', 'U10392', 'U12635', 'U09544', 'U10928',
       'U05443', 'U13379', 'U01138', 'U04280', 'U09447', 'U01147',
       'U11424', 'U03444', 'U10877', 'U12591', 'U14098', 'U13900',
       'U08977', 'U03920', 'U02504', 'U12613', 'U12037', 'U13771',
       'U02978', 'U01342', 'U00334', 'U12255', 'U11715', 'U05689',
       'U13578', 'U11978', 'U04233', 'U11315', 'U08699', 'U12488',
       'U04495', 'U05583', 'U13290', 'U14885', 'U02574', 'U12908',
       'U02719', 'U08091', 'U11015', 'U09591', 'U08118', 'U13516',
       'U03336', 'U05092', 'U07906', 'U04527', 'U09502', 'U05273',
       'U10874', 'U07214', 'U13956', 'U12236', 'U06142', 'U09555',
       'U07238', 'U13982', 'U11237', 'U03116', 'U14360', 'U05550',
       'U13183', 'U13475', 'U07607', 'U14537', 'U04584', 'U04521',
       'U02064', 'U02418', 'U14196', 'U07803'], dtype=object)

In [33]:
df['product_purchased'].unique()

array(['NPP', 'Marshall Kilburn II', 'Ultimate Ears Roll 2',
       'Marshall Tufton', 'Ultimate Ears Boom 2', 'Sennheiser HD 250BT',
       'Tribit StormBox Blast', 'Harman Kardon Aura Studio 3'],
      dtype=object)

In [14]:
# Checking which channel has high engagement
df[['device_type', 'time_spent']]

   device_type  time_spent
0      Desktop        2.65
1       Mobile        9.53
2       Mobile        2.94
3       Mobile       16.76
4      Desktop        6.28
..         ...         ...
95     Desktop        1.96
96      Mobile       16.45
97      Tablet        5.76
98      Mobile        9.00
99      Tablet       14.82

[100 rows x 2 columns]

In [17]:
df['device_type'].unique()

array(['Desktop', 'Mobile', 'Tablet'], dtype=object)

In [34]:
df.head()

,user_id,session_id,sign_in,name,demographic_age,demographic_age_group,demographic_gender,email,location,country,...,pages_visited,conversion_flag,conversion_type,traffic_source,product_purchased,revenue_$,payment_type,card_type,coupon_applied,bounce_flag
0,U10477,S000001,Email,Victor Navarro-Noël,31,Adult,Female,victornavarronoël251@hotmail.com,Rome,Italy,...,7,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,1
1,U01536,S000002,Email,王秀云,39,Adult,Female,王秀云617@gmail.com,Madrid,Spain,...,5,0,NCT,Social,NPP,0.0,NPT,NCAT,ND,0
2,U00107,S000003,Guest,Ucchal Sabharwal,68,Old,Male,Not Provided,Manchester,UK,...,7,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,0
3,U13886,S000004,Email,Virginie Schmitt,72,Old,Female,virginieschmitt827@gmail.com,Sydney,Australia,...,10,0,NCT,Social,NPP,0.0,NPT,NCAT,ND,0
4,U05926,S000005,Email,Cynthia Drake,51,Adult,No Answer,cynthiadrake47@hotmail.com,Mumbai,India,...,6,0,NCT,Organic,NPP,0.0,NPT,NCAT,ND,0

In [29]:
channel_engagement = df.groupby('device_type').agg(total_timespent=pd.NamedAgg(column='time_spent', aggfunc='sum'), avg_timespent=pd.NamedAgg(column='time_spent', aggfunc='mean')).round(2).sort_values(by='total_timespent', ascending=False)
channel_engagement

             total_timespent  avg_timespent
device_type
Mobile                680.30          11.15
Desktop               342.39          11.04
Tablet                104.77          13.10